// 100개의 초등 저학년용 기초 영어 단어. 같은 category 안에서 오답 보기를 만듭니다.
window.QUESTIONS = [
  {word:'cat',emoji:'🐱',ko:'고양이',category:'animal'}, {word:'dog',emoji:'🐶',ko:'강아지',category:'animal'},
  {word:'rabbit',emoji:'🐰',ko:'토끼',category:'animal'}, {word:'bear',emoji:'🐻',ko:'곰',category:'animal'},
  {word:'lion',emoji:'🦁',ko:'사자',category:'animal'}, {word:'tiger',emoji:'🐯',ko:'호랑이',category:'animal'},
  {word:'monkey',emoji:'🐵',ko:'원숭이',category:'animal'}, {word:'pig',emoji:'🐷',ko:'돼지',category:'animal'},
  {word:'cow',emoji:'🐮',ko:'소',category:'animal'}, {word:'horse',emoji:'🐴',ko:'말',category:'animal'},
  {word:'sheep',emoji:'🐑',ko:'양',category:'animal'}, {word:'mouse',emoji:'🐭',ko:'쥐',category:'animal'},
  {word:'frog',emoji:'🐸',ko:'개구리',category:'animal'}, {word:'duck',emoji:'🦆',ko:'오리',category:'animal'},
  {word:'chicken',emoji:'🐔',ko:'닭',category:'animal'}, {word:'penguin',emoji:'🐧',ko:'펭귄',category:'animal'},
  {word:'bird',emoji:'🐦',ko:'새',category:'animal'}, {word:'fish',emoji:'🐟',ko:'물고기',category:'animal'},
  {word:'whale',emoji:'🐳',ko:'고래',category:'animal'}, {word:'dolphin',emoji:'🐬',ko:'돌고래',category:'animal'},
  {word:'elephant',emoji:'🐘',ko:'코끼리',category:'animal'}, {word:'giraffe',emoji:'🦒',ko:'기린',category:'animal'},
  {word:'zebra',emoji:'🦓',ko:'얼룩말',category:'animal'}, {word:'fox',emoji:'🦊',ko:'여우',category:'animal'},
  {word:'turtle',emoji:'🐢',ko:'거북이',category:'animal'},

  {word:'apple',emoji:'🍎',ko:'사과',category:'food'}, {word:'banana',emoji:'🍌',ko:'바나나',category:'food'},
  {word:'grape',emoji:'🍇',ko:'포도',category:'food'}, {word:'strawberry',emoji:'🍓',ko:'딸기',category:'food'},
  {word:'watermelon',emoji:'🍉',ko:'수박',category:'food'}, {word:'peach',emoji:'🍑',ko:'복숭아',category:'food'},
  {word:'orange',emoji:'🍊',ko:'오렌지',category:'food'}, {word:'lemon',emoji:'🍋',ko:'레몬',category:'food'},
  {word:'carrot',emoji:'🥕',ko:'당근',category:'food'}, {word:'corn',emoji:'🌽',ko:'옥수수',category:'food'},
  {word:'bread',emoji:'🍞',ko:'빵',category:'food'}, {word:'cheese',emoji:'🧀',ko:'치즈',category:'food'},
  {word:'egg',emoji:'🥚',ko:'달걀',category:'food'}, {word:'rice',emoji:'🍚',ko:'밥',category:'food'},
  {word:'milk',emoji:'🥛',ko:'우유',category:'food'}, {word:'cookie',emoji:'🍪',ko:'쿠키',category:'food'},
  {word:'cake',emoji:'🍰',ko:'케이크',category:'food'}, {word:'ice cream',emoji:'🍦',ko:'아이스크림',category:'food'},
  {word:'pizza',emoji:'🍕',ko:'피자',category:'food'}, {word:'hamburger',emoji:'🍔',ko:'햄버거',category:'food'},

  {word:'book',emoji:'📕',ko:'책',category:'thing'}, {word:'pencil',emoji:'✏️',ko:'연필',category:'thing'},
  {word:'bag',emoji:'🎒',ko:'가방',category:'thing'}, {word:'chair',emoji:'🪑',ko:'의자',category:'thing'},
  {word:'clock',emoji:'⏰',ko:'시계',category:'thing'}, {word:'phone',emoji:'📱',ko:'전화기',category:'thing'},
  {word:'camera',emoji:'📷',ko:'카메라',category:'thing'}, {word:'key',emoji:'🔑',ko:'열쇠',category:'thing'},
  {word:'ball',emoji:'⚽',ko:'공',category:'thing'}, {word:'doll',emoji:'🪆',ko:'인형',category:'thing'},
  {word:'kite',emoji:'🪁',ko:'연',category:'thing'}, {word:'balloon',emoji:'🎈',ko:'풍선',category:'thing'},
  {word:'gift',emoji:'🎁',ko:'선물',category:'thing'}, {word:'umbrella',emoji:'☂️',ko:'우산',category:'thing'},
  {word:'cup',emoji:'🥤',ko:'컵',category:'thing'}, {word:'spoon',emoji:'🥄',ko:'숟가락',category:'thing'},
  {word:'toothbrush',emoji:'🪥',ko:'칫솔',category:'thing'}, {word:'bed',emoji:'🛏️',ko:'침대',category:'thing'},
  {word:'door',emoji:'🚪',ko:'문',category:'thing'}, {word:'television',emoji:'📺',ko:'텔레비전',category:'thing'},

  {word:'sun',emoji:'☀️',ko:'해',category:'nature'}, {word:'moon',emoji:'🌙',ko:'달',category:'nature'},
  {word:'star',emoji:'⭐',ko:'별',category:'nature'}, {word:'cloud',emoji:'☁️',ko:'구름',category:'nature'},
  {word:'rain',emoji:'🌧️',ko:'비',category:'nature'}, {word:'snow',emoji:'❄️',ko:'눈',category:'nature'},
  {word:'rainbow',emoji:'🌈',ko:'무지개',category:'nature'}, {word:'tree',emoji:'🌳',ko:'나무',category:'nature'},
  {word:'flower',emoji:'🌷',ko:'꽃',category:'nature'}, {word:'leaf',emoji:'🍃',ko:'나뭇잎',category:'nature'},
  {word:'mountain',emoji:'⛰️',ko:'산',category:'nature'}, {word:'ocean',emoji:'🌊',ko:'바다',category:'nature'},
  {word:'fire',emoji:'🔥',ko:'불',category:'nature'}, {word:'earth',emoji:'🌍',ko:'지구',category:'nature'},
  {word:'house',emoji:'🏠',ko:'집',category:'nature'},

  {word:'car',emoji:'🚗',ko:'자동차',category:'move'}, {word:'bus',emoji:'🚌',ko:'버스',category:'move'},
  {word:'train',emoji:'🚆',ko:'기차',category:'move'}, {word:'airplane',emoji:'✈️',ko:'비행기',category:'move'},
  {word:'ship',emoji:'🚢',ko:'배',category:'move'}, {word:'bicycle',emoji:'🚲',ko:'자전거',category:'move'},
  {word:'rocket',emoji:'🚀',ko:'로켓',category:'move'}, {word:'taxi',emoji:'🚕',ko:'택시',category:'move'},
  {word:'shoe',emoji:'👟',ko:'신발',category:'wear'}, {word:'hat',emoji:'🧢',ko:'모자',category:'wear'},
  {word:'shirt',emoji:'👕',ko:'셔츠',category:'wear'}, {word:'dress',emoji:'👗',ko:'원피스',category:'wear'},
  {word:'glasses',emoji:'👓',ko:'안경',category:'wear'}, {word:'socks',emoji:'🧦',ko:'양말',category:'wear'},
  {word:'hand',emoji:'✋',ko:'손',category:'body'}, {word:'eye',emoji:'👁️',ko:'눈',category:'body'},
  {word:'ear',emoji:'👂',ko:'귀',category:'body'}, {word:'nose',emoji:'👃',ko:'코',category:'body'},
  {word:'mouth',emoji:'👄',ko:'입',category:'body'}, {word:'foot',emoji:'🦶',ko:'발',category:'body'}
];
